#!/usr/bin/env node
// Builds the deployable site into dist/. Used by both Vercel (vercel.json
// buildCommand) and GitHub Pages (.github/workflows/deploy.yml), so the two
// hosts serve identical output during the migration.
//
//   1. Copies only the public site files (no tests, workflows, node_modules).
//   2. Rewrites absolute URLs (canonical, og:url, JSON-LD, sitemap, robots)
//      from the checked-in GitHub Pages address to SITE_URL.
//   3. Writes dist/js/config.js from the Stripe environment variables.
//   4. Sets the Google Search Console verification tag on the home page.
//
// Environment variables (all optional):
//   SITE_URL                 Public base URL, e.g. https://example.com/
//                            On Vercel, defaults to the production domain.
//   ENABLE_STRIPE            "true" enables the Finalize (paid) button. The
//                            server side also needs STRIPE_SECRET_KEY and
//                            STRIPE_PRICE_ID (read by /api at runtime).
//   PRICE_LABEL              Price shown next to Finalize, e.g. "$9.99".
//   GOOGLE_SITE_VERIFICATION Google Search Console "HTML tag" token. Either
//                            the content value or the whole <meta> tag;
//                            comma-separate several. Replaces the token
//                            checked into index.html.

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DIST = path.join(ROOT, 'dist');

// Files and directories that make up the public site.
const PUBLIC = [
  'index.html',
  'calculator.html',
  'guidelines.html',
  'robots.txt',
  'sitemap.xml',
  'css',
  'js',
  'data',
];

// The base URL written in the source files.
const SOURCE_SITE_URL = 'https://tborer.github.io/ne-child-support-calc/';

// Files whose absolute URLs get rewritten.
const URL_FILES = ['index.html', 'calculator.html', 'guidelines.html', 'robots.txt', 'sitemap.xml'];

function resolveSiteUrl() {
  let url = process.env.SITE_URL;
  if (!url && process.env.VERCEL_PROJECT_PRODUCTION_URL) {
    url = `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`;
  }
  if (!url) return SOURCE_SITE_URL;
  return url.endsWith('/') ? url : `${url}/`;
}

/**
 * Tokens from GOOGLE_SITE_VERIFICATION. Accepts the bare token or the full
 * tag Search Console shows (<meta name="google-site-verification" content="…" />),
 * comma-separated for more than one.
 */
function verificationTokens(value) {
  if (!value) return [];
  return value.split(',')
    .map((part) => {
      const match = part.match(/content\s*=\s*["']([^"']+)["']/i);
      return (match ? match[1] : part).trim();
    })
    .filter((token) => /^[\w-]{10,100}$/.test(token));
}

const VERIFICATION_TAG = /^[ \t]*<meta name="google-site-verification"[^>]*>[ \t]*\n/m;

function applyVerification(file, tokens) {
  const html = fs.readFileSync(file, 'utf8');
  if (!VERIFICATION_TAG.test(html)) throw new Error(`No google-site-verification tag in ${file}`);
  const tags = tokens
    .map((token) => `  <meta name="google-site-verification" content="${token}" />\n`)
    .join('');
  fs.writeFileSync(file, html.replace(VERIFICATION_TAG, tags));
}

function build() {
  fs.rmSync(DIST, { recursive: true, force: true });
  fs.mkdirSync(DIST);
  for (const entry of PUBLIC) {
    fs.cpSync(path.join(ROOT, entry), path.join(DIST, entry), { recursive: true });
  }

  const siteUrl = resolveSiteUrl();
  if (siteUrl !== SOURCE_SITE_URL) {
    for (const file of URL_FILES) {
      const target = path.join(DIST, file);
      const text = fs.readFileSync(target, 'utf8');
      fs.writeFileSync(target, text.split(SOURCE_SITE_URL).join(siteUrl));
    }
  }

  const rawVerification = process.env.GOOGLE_SITE_VERIFICATION;
  const tokens = verificationTokens(rawVerification);
  if (rawVerification && !tokens.length) {
    console.warn('GOOGLE_SITE_VERIFICATION is set but has no valid token; keeping the checked-in tag.');
  }
  if (tokens.length) applyVerification(path.join(DIST, 'index.html'), tokens);

  const config = {
    ENABLE_STRIPE: process.env.ENABLE_STRIPE === 'true',
    PRICE_LABEL: process.env.PRICE_LABEL || '',
  };
  fs.writeFileSync(
    path.join(DIST, 'js', 'config.js'),
    '// Generated by scripts/build.js — do not edit.\n' +
      `window.APP_CONFIG = ${JSON.stringify(config, null, 2)};\n`
  );

  console.log(`Built dist/ for ${siteUrl} (Stripe ${config.ENABLE_STRIPE ? 'on' : 'off'}, ` +
    `Google verification ${tokens.length ? `${tokens.length} token(s) from env` : 'checked-in tag'})`);
}

build();
