#!/usr/bin/env node
// Builds the deployable site into dist/. Used by both Vercel (vercel.json
// buildCommand) and GitHub Pages (.github/workflows/deploy.yml), so the two
// hosts serve identical output during the migration.
//
//   1. Copies only the public site files (no tests, workflows, node_modules).
//   2. Rewrites absolute URLs (canonical, og:url, JSON-LD, sitemap, robots)
//      from the checked-in GitHub Pages address to SITE_URL.
//   3. Writes dist/js/config.js from the Stripe environment variables.
//
// Environment variables (all optional):
//   SITE_URL                 Public base URL, e.g. https://example.com/
//                            On Vercel, defaults to the production domain.
//   ENABLE_STRIPE            "true" enables the Finalize (paid) button. The
//                            server side also needs STRIPE_SECRET_KEY and
//                            STRIPE_PRICE_ID (read by /api at runtime).
//   PRICE_LABEL              Price shown next to Finalize, e.g. "$9.99".

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DIST = path.join(ROOT, 'dist');

// Files and directories that make up the public site.
const PUBLIC = [
  'index.html',
  'calculator.html',
  'guidelines.html',
  'robots.txt',
  'sitemap.xml',
  'css',
  'js',
  'data',
];

// The base URL written in the source files.
const SOURCE_SITE_URL = 'https://tborer.github.io/ne-child-support-calc/';

// Files whose absolute URLs get rewritten.
const URL_FILES = ['index.html', 'calculator.html', 'guidelines.html', 'robots.txt', 'sitemap.xml'];

function resolveSiteUrl() {
  let url = process.env.SITE_URL;
  if (!url && process.env.VERCEL_PROJECT_PRODUCTION_URL) {
    url = `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`;
  }
  if (!url) return SOURCE_SITE_URL;
  return url.endsWith('/') ? url : `${url}/`;
}

function build() {
  fs.rmSync(DIST, { recursive: true, force: true });
  fs.mkdirSync(DIST);
  for (const entry of PUBLIC) {
    fs.cpSync(path.join(ROOT, entry), path.join(DIST, entry), { recursive: true });
  }

  const siteUrl = resolveSiteUrl();
  if (siteUrl !== SOURCE_SITE_URL) {
    for (const file of URL_FILES) {
      const target = path.join(DIST, file);
      const text = fs.readFileSync(target, 'utf8');
      fs.writeFileSync(target, text.split(SOURCE_SITE_URL).join(siteUrl));
    }
  }

  const config = {
    ENABLE_STRIPE: process.env.ENABLE_STRIPE === 'true',
    PRICE_LABEL: process.env.PRICE_LABEL || '',
  };
  fs.writeFileSync(
    path.join(DIST, 'js', 'config.js'),
    '// Generated by scripts/build.js — do not edit.\n' +
      `window.APP_CONFIG = ${JSON.stringify(config, null, 2)};\n`
  );

  console.log(`Built dist/ for ${siteUrl} (Stripe ${config.ENABLE_STRIPE ? 'on' : 'off'})`);
}

build();
